FROM python:3.10-slim

# Installiere Chromium, Chromedriver, ca-certificates, GIT ...
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        chromium \
        chromium-driver \
        git \
        ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

ENV CHROME_BINARY=/usr/bin/chromium

CMD ["python", "--version"]