name: Build Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU (für multi-arch builds, optional)
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          # Hier manuell in Kleinbuchstaben.
          # Statt "ProfessorSchuster/ProfessorSchuster.github.io" also z.B. "professorschuster/professorschuster-github-io"
          docker build \
            -t ghcr.io/professorschuster/professorschuster-github-io:latest \
            .

      - name: Push Docker image
        run: |
          docker push ghcr.io/professorschuster/professorschuster-github-io:latest
