name: Update Preis

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '5 * * * *'  # stündlich, anpassen wie du möchtest
  workflow_dispatch:

permissions:
  contents: write
  packages: read   # wir müssen das Image aus GHCR pullen können

jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/professorschuster/professorschuster-github-io:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run update script
        run: |
          # Hier liegt dein Code im Container unter /github/workspace
          # Du kannst direkt "python update_price.py" aufrufen,
          # wenn dein Script den Template-Pfad relativ findet.
          python update_price.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add index.html
          git commit -m "Automatische Aktualisierung des Preises" || echo "Keine Änderungen"
          git push